language: python

branches:
  only:
    - master

python:
  - "3.6"
env:
  - PYTORCH_VERSION=master
  - PYTORCH_VERSION=stable

install:
  - if [[ $PYTORCH_VERSION = "master" ]]; then
      pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
      python setup.py build develop;
    else
      pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl;
    fi

script:
  - python -c "import torch; print('PyTorch Version:', torch.__version__)"
  - python -m unittest discover

matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8 flake8-print
      script: flake8
    - env: DOCS_CHECK
      addons:
        apt_packages:
          - pandoc
      python: "3.6"
      install: pip install IPython ipykernel sphinx sphinx_rtd_theme nbsphinx m2r
      script: python setup.py build_sphinx
